directory: /stuff/beets/music
library: /stuff/beets/musiclibrary.db

paths:
  # default: $albumartist/$year - $album/$track $artist - $title
  default: %the{$albumartist}/$year - $album/$track $artist - $title
  singleton: Singletons/$artist - $title
  comp: $genre/$album/$track $title
  albumtype:soundtrack: Soundtracks/$album/$track $artist - $title

plugins: discogs duplicates fetchart importadded the

discogs:
  # pip install discogs-client
  # Useful for classical music:
  index_tracks: yes

fetchart:
  # pip install requests
  cautious: true

importadded:
  preserve_mtimes: yes
  preserve_write_mtimes: yes
