directory: /stuff/beets/music
library: /stuff/beets/musiclibrary.db

art_filename: cover
asciify_paths: yes
per_disc_numbering: yes
threaded: yes

paths:
  # default: $albumartist/$year - $album/$track $artist - $title
  default: %the{$albumartist}/$year - $album%aunique{}/%if{$multidisc,$disc-}$track $artist - $title
  #singleton: Singletons/$artist - $title
  singleton: %the{$albumartist}/single - $artist - $title/$artist - $title
  comp: Compilations/$album%aunique{}/%if{$multidisc,$disc-}$track $artist - $title
  albumtype:soundtrack: Soundtracks/$album%aunique{}/%if{$multidisc,$disc-}$track $artist - $title

import:
  write: yes
  copy: yes
  move: no
  resume: ask
  #incremental: yes
  log: beetslog.log

ignore: .AppleDouble ._* *~ .DS_Store

plugins: [
  discogs,
  duplicates,
  embedart,
  fetchart,
  ftintitle,
  importadded,
  inline,
  the,
]

discogs:
  # pip install discogs-client
  # Useful for classical music:
  index_tracks: yes

fetchart:
  # pip install requests
  cautious: true

ftintitle:
  auto: yes
  format: (feat. {0})

importadded:
  preserve_mtimes: yes
  preserve_write_mtimes: yes

item_fields:
  multidisc: 1 if disctotal > 1 else 0
