format = """
[](#9A348E)\
$jobs\
$os\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$python\
$rust\
$scala\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
$time\
[ ](fg:#33658A)\
$cmd_duration\
"""

# Timeout for commands executed by starship (ms)
command_timeout = 2000

# Disable the blank line at the start of the prompt
# add_newline = false

# Backgrounded processes
[jobs]
style = "bg:#9A348E"
symbol = '✦'
format = '[$number$symbol ]($style)'

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
# show_always = true
show_always = false
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""
"workspace" = ""
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol( $version) ]($style)'

[docker_context]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol( $version) ]($style)'

[elm]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol( $version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#FCA17D"
truncation_length = 30
format = '[ $symbol $branch ]($style)'

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
#    
style = "bg:#FCA17D"
# style = "bg:#fb7d4b"
# style = "bg:#fb7d4b fg:#ff0000"
# style = "fg:#000000 bg:#FCA17D"
# style = "fg:#ff0000 bg:#FCA17D"
# staged = ''
# modified = ''
# untracked = '?'
# format = '[$all_status$ahead_behind ]($style)'
format = '[$all_status$ahead_behind]($style)'
# format = '[$all_status$ahead_behind]($style)[ ](bg:#FCA17D)'
# format = '[$all_status$ahead_behind]($style)[ ](bg:#FCA17D)'
# format = '[](bg:#fb7d4b fg:#FCA17D)[$all_status$ahead_behind]($style)[](bg:#FCA17D fg:#fb7d4b)'

[golang]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol( $version) ]($style)'

[gradle]
style = "bg:#86BBD8"
format = '[ $symbol( $version) ]($style)'

[haskell]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol( $version) ]($style)'

[java]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol( $version) ]($style)'

[julia]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol( $version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol( $version) ]($style)'

[nim]
symbol = "󰆥"
style = "bg:#86BBD8"
format = '[ $symbol( $version) ]($style)'

[python]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol( $virtualenv) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol( $version) ]($style)'

[scala]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol( $version) ]($style)'

[cmd_duration]
min_time = 2000
show_milliseconds = true
#format = ' $duration ($style)'
format = '[](fg:#333333)[$duration](bg:#333333)[](fg:#333333) ($style)'

[time]
disabled = false
# time_format = "%R" # Hour:Minute Format
time_format = "%T" # Hour:Minute:Second Format
style = "bg:#33658A"
format = '[ $time ]($style)'
